aca_shop_home:
    path:     /
    defaults: { _controller: AcaShopBundle:Home:index }


  #This will get hit when the user types in a username and a password.
aca_shop_login:
    path:     /login_user
    defaults: { _controller: AcaShopBundle:Home:login }


aca_shop_logout:
    path:     /logout
    defaults: { _controller: AcaShopBundle:Home:logout }


aca_shop_product:
  path:       /product
  defaults: { _controller: AcaShopBundle:Product:show }


aca_shop_hello:
    path:     /hello/{name}
    defaults: { _controller: AcaShopBundle:Default:index }

aca_shop_add_cart:
    path:   /add_cart
    defaults: { _controller: AcaShopBundle:Cart:add }

aca_shop_display_cart:
    path:   /cart
    defaults: { _controller: AcaShopBundle:Cart:show }

aca_shop_remove_cart:
    path:   /remove_cart
    defaults: { _controller: AcaShopBundle:Cart:remove }

aca_shop_update_cart:
    path:   /update_cart
    defaults: { _controller: AcaShopBundle:Cart:update }

aca_shop_shipping_address:
    path:   /shipping_address
    defaults: { _controller: AcaShopBundle:Cart:shippingaddress }

aca_shop_place_order:
    path:   /place_order
    defaults: { _controller: AcaShopBundle:Order:placeorder }

aca_shop_receipt:
    path:   /receipt
    defaults: { _controller: AcaShopBundle:Receipt:receipt }
